### ISSUE TITLE
Possible incorrect rendering in log?

### ISSUE THREAD

**Issue by experimental36** [Tesena-smart-testing/WatchUI#117]
**Describe the bug**
I am thinking whether there is a slight bug with the choice of which image is rendered to the test log when the images don't match:
- if there is an error, target image is shown instead of concatenated baseline and target

**To Reproduce**

Case 1
1. Execute test that uses Compare Images and will surely PASS
2. Check log

Case 2
1. Execute test that uses Compare Images and will surely FAIL
2. Check log

**Expected behavior**
Case 1: The log contains concatenated baseline+target image, while I believe it should be only target.
Case 2: The log contains target image, while I believe it should be concatenated baseline+target image.

**Additional context**
I am guessing the error is in the _if_ statement:
https://github.com/Tesena-smart-testing/WatchUI/blob/master/WatchUI/keywords/Image.py#L100

Possible solution:

```
        if score < ssim:
            img_diff: Any = cv.hconcat([base_image, target_image])
            cv.imwrite(url, img_diff)        
            self.set_log_message(
                work_object="Image", type_of_messages="Error", path_to_image=url
            )
        else:
            cv.imwrite(url, target_image)
            self.set_log_message(
                work_object="Image", type_of_messages="Info", path_to_image=url
            )
```

**Comment by procesor2017** [comment]
Hi, 
that's an interesting point. 
For the first case:
Here it is correct, there is really a concatenate to occur, because of the SSIM option. 
E.g. If you want the test to pass even if there are only 30% differences. You set the SSIM. But what if you want to look at the comparison of these images? Thats why we concatenate image to log.

It seems to me that maybe we could add an argument where the person could choose what type of image they want (linked or just one), but I just don't know if that would be a useless argument, because if the test passes, how many people will then look at whether there is an concatenate image or not? Besides the people who just need it to be there?

For the second case.
Here it's really illogical. So I've added a link between the original and the real image directly to the log.

**Comment by janegermaier** [comment]
Version v2.0.12 is up. For changes just update your local library :+1:

**Comment by experimental36** [comment]
Hello,
thank you for looking into the issue and explaining your thoughts. It looks like a good solution.

My suggestion was actually just reversing the code for cv.imwrite between if and else clauses, thinking that was the original intention. But how it is now makes more sense. 

Not yet sure about the proposed argument though. Perhaps after using the library more I will get a better feel for the use cases. But it is something to consider indeed.

**Comment by procesor2017** [comment]
No problem,
I´m happy for everyone who use ours library and wanna to change anything for better usage.

Ty for your feedback :smile:

**Comment by experimental36** [comment]
Excellent, thank you as well for your work on this great library! 😄 Might have a few suggestions coming up.
